import { readFileSafe } from "../../io/fs.js";

const BLOCK_START = (section: string) => `<!-- contextkit:start:${section} -->`;
const BLOCK_END = (section: string) => `<!-- contextkit:end:${section} -->`;

/**
 * Check if a file contains contextkit managed markers.
 */
export function hasManagedBlocks(content: string): boolean {
  return content.includes("<!-- contextkit:start:");
}

/**
 * Check if a file was generated by contextkit.
 */
export function isGenerated(content: string): boolean {
  return content.includes("<!-- generated-by: contextkit -->");
}

/**
 * Replace managed blocks in existing content while preserving user content.
 * Returns the merged content, or null if no managed blocks were found.
 */
export function replaceManagedBlocks(
  existingContent: string,
  newBlocks: Record<string, string>
): string | null {
  if (!hasManagedBlocks(existingContent)) return null;

  let result = existingContent;

  for (const [section, newContent] of Object.entries(newBlocks)) {
    const startMarker = BLOCK_START(section);
    const endMarker = BLOCK_END(section);
    const startIdx = result.indexOf(startMarker);
    const endIdx = result.indexOf(endMarker);

    if (startIdx !== -1 && endIdx !== -1) {
      const before = result.substring(0, startIdx);
      const after = result.substring(endIdx + endMarker.length);
      result = `${before}${startMarker}\n${newContent}\n${endMarker}${after}`;
    }
  }

  return result;
}

/**
 * Wrap content in managed block markers.
 */
export function wrapInManagedBlock(section: string, content: string): string {
  return `${BLOCK_START(section)}\n${content}\n${BLOCK_END(section)}`;
}

/**
 * Determine merge strategy for a file.
 */
export function determineMergeStrategy(
  existingPath: string
): "create" | "merge-blocks" | "skip" {
  const content = readFileSafe(existingPath);
  if (!content) return "create";
  if (hasManagedBlocks(content)) return "merge-blocks";
  return "skip";
}
